import type { RiskFlags, GenerativeRates } from "@/types"

export function generateRecommendations(flags: RiskFlags, rates: GenerativeRates): string[] {
  const recs: string[] = []

  if (flags.noAppealMechanism)
    recs.push("Establish a formal appeal process with human review and response deadlines.")
  if (flags.noReentryMechanism)
    recs.push("Design re-entry pathways that allow affected subjects to return after negative outcomes.")
  if (flags.noContextRecovery)
    recs.push("Introduce structured mechanisms for subjects to present contextual information.")
  if (flags.personhoodSubstitution)
    recs.push("Redesign decision outputs to treat scores as contextual indicators, not identity substitutes.")
  if (flags.opaqueScoring)
    recs.push("Implement explainability requirements: decision rationale must be legible to affected parties.")
  if (flags.measurementAsOntology)
    recs.push("Separate measurement from ontological claims. Scores indicate — they do not define.")
  if (flags.proxyDiscrimination)
    recs.push("Audit all proxy variables for discriminatory correlation. Remove or correct biased features.")
  if (flags.responsibilityShift)
    recs.push("Redistribute accountability to institutional actors and structural conditions.")
  if (flags.historicalLockIn)
    recs.push("Introduce counter-historical weighting to break self-reinforcing cycles of exclusion.")
  if (flags.noHumanReview)
    recs.push("Mandate human review at all consequential decision points.")
  if (flags.noPeriodicReaudit)
    recs.push("Schedule regular independent audits of system outcomes and bias patterns.")
  if (flags.excessiveAutomation)
    recs.push("Limit automation to pre-selection support roles; require human judgment for final decisions.")
  if (flags.futureClosure)
    recs.push("Redesign output categories to preserve future possibilities rather than fix permanent status.")
  if (flags.surveillanceExpansion)
    recs.push("Restrict data collection to the minimum necessary for the stated purpose. Enforce scope limits.")
  if (flags.shortTermKPI)
    recs.push("Replace short-term KPIs with long-term developmental indicators and longitudinal tracking.")
  if (flags.moralizationOfLowScore)
    recs.push("Remove moral language from score outputs. Low scores must indicate conditions, not character.")
  if (flags.classificationAsExclusion)
    recs.push("Convert exclusionary classifications into support routing and targeted resource allocation.")
  if (flags.biologicalFixation)
    recs.push("Remove fixed biological or genetic characteristics from scoring inputs.")
  if (flags.povertyPenalty)
    recs.push("Audit for economic proxy variables that systematically disadvantage lower-income subjects.")
  if (flags.disabilityPenalty)
    recs.push("Remove disability proxies and introduce universal design standards for all subjects.")

  if (rates.RCR < 2)
    recs.push("Significantly strengthen return capability — the system currently provides minimal recovery pathways.")
  if (rates.FGR < 2)
    recs.push("Redesign to expand reachable states for subjects rather than narrow future options.")
  if (rates.SRGR < 2)
    recs.push("Shift responsibility distribution toward institutions and environmental conditions.")
  if (rates.TIGR < 2)
    recs.push("Allow time for subject development, repair, and maturation before re-evaluation.")

  return recs.length > 0 ? recs : ["No critical redesign requirements identified. Maintain re-audit schedule."]
}
