"use client"

import { useState } from "react"
import { useMADAN } from "@/lib/madan/store"
import { generateMarkdownReport, generateJSONExport } from "@/lib/madan/reportGenerator"

const SAMPLE_REPORT = `# DDAT Structured Audit Report — AI Hiring System Audit
**Generated:** 2026-06-30
**System Type:** labor
**Directional Judgment:** High future-closure risk. Requires structural re-entry and responsibility redesign before deployment in high-stakes hiring contexts.
**DCR Directional Audit Index:** −1.84 / ±5.00

---

## Executive Summary

The Multi-Perspective Audit Module conducted a full twelve-perspective structured audit of the **AI Hiring System Audit**. The audit produced a DCR Directional Audit Index of **−1.84**, yielding a directional judgment of **High future-closure risk**.

The audit identified 4 future-closure risks, 3 main contradictions across audit perspectives, and a reachable-state impact score of −2.1.

---

## Nine Generative-Rate Evaluations

| Rate | Label | Score | Risk |
|------|-------|-------|------|
| IGR | Information Generation Rate | −2 | High |
| PDFR | Pre-Difference Field Generation Rate | −3 | High |
| MGR | Meaning / Truth-Feeling Generation Rate | −1 | Moderate |
| D-RGR | Division-of-Labor Relational Generation Rate | −2 | High |
| SRGR | Responsibility Generation Rate | −3 | High |
| TIGR | Temporal Integration Generation Rate | −1 | Moderate |
| RCR | Reality / Bodily Return Capacity Rate | −2 | High |
| FGR | Freedom Generation Rate | −1 | Moderate |
| HGR | Historical Generation Rate | −2 | High |

**IGR (−2):** The system filters applicant information through engagement metrics and keyword-matching, systematically excluding non-standard career paths, care-work gaps, and non-credentialed expertise. Information about the applicant that falls outside the scoring vocabulary is treated as non-existent.

**PDFR (−3):** Applicants are classified into ranked tiers at the resume screening stage, before any contextual interaction. The scoring form closes the possibility space at the earliest decision point, with no mechanism for later re-entry into higher tiers.

**SRGR (−3):** The vendor contract designates the algorithmic output as a "decision support tool," while the employer treats it as the de facto hiring criterion. No institutional actor holds traceable responsibility for classification errors or systemic exclusion.

---

## Main Contradictions

1. The system claims to reduce human bias while embedding historical hiring patterns as training data — reproducing rather than correcting structural exclusion.
2. Candidates are told outcomes are "decision support," but no human review of algorithmic rankings occurs in practice.
3. An appeal mechanism exists on paper, but requires applicants to obtain the score rationale — which is not disclosed.

---

## Future-Closure Risks

1. Applicants rejected at the resume stage have no pathway to re-enter the same role within the same system, regardless of elapsed time or changed circumstances.
2. Gaps in employment history — including caregiving, disability, and educational retraining — are treated as negative signals with no contextual override.
3. Candidates from institutions underrepresented in historical hiring data receive systematically lower similarity scores.
4. The absence of a structured explanation mechanism means affected persons cannot identify or contest the basis for rejection.

---

## Design Corrections

1. Require a human review stage before final rejection for all candidates who cleared minimum qualifications.
2. Implement a formal re-entry pathway with a defined interval (recommended: 6 months minimum, not 12).
3. Disclose score rationale to all rejected candidates as a standard right, not upon request.
4. Audit training data for historical underrepresentation before each deployment cycle.
5. Assign explicit institutional responsibility to the procurement body for systemic exclusion outcomes.

---

## Directional Judgment

**DCR Directional Audit Index:** −1.84
**Reachable-State Impact:** Reducing (−2.1)

This system, as currently designed, contracts the reachable state space of affected populations. The combination of early-stage classification, opaque rationale, absent re-entry design, and displaced responsibility produces cumulative future-closure risk that exceeds what can be addressed by surface-level interface changes. Structural redesign of the scoring form, responsibility allocation, and appeal mechanism is required before deployment in consequential hiring contexts.

---

*Generated by DDAT Studio — Multi-Perspective Audit Module*
*This report is a structured audit hypothesis — not a legal finding or ethical certification.*
`

function SampleReportView() {
  const lines = SAMPLE_REPORT.split("\n")
  return (
    <div className="font-mono text-[11px] leading-relaxed text-gray-800 space-y-0.5 overflow-auto max-h-[560px] bg-gray-50 border border-gray-200 p-5">
      {lines.map((line, i) => {
        if (line.startsWith("# ")) {
          return <p key={i} className="text-[13px] font-bold text-gray-900 mt-2 mb-1">{line.replace(/^# /, "")}</p>
        }
        if (line.startsWith("## ")) {
          return <p key={i} className="text-[11px] font-bold text-gray-700 uppercase tracking-wider mt-4 mb-1 border-b border-gray-200 pb-1">{line.replace(/^## /, "")}</p>
        }
        if (line.startsWith("| Rate")) {
          return <p key={i} className="text-[10px] font-bold text-gray-500">{line}</p>
        }
        if (line.startsWith("|---")) {
          return null
        }
        if (line.startsWith("| ")) {
          return <p key={i} className="text-[10px] text-gray-700">{line}</p>
        }
        if (line.startsWith("**") && line.endsWith("**")) {
          return <p key={i} className="font-semibold text-gray-900">{line.replace(/\*\*/g, "")}</p>
        }
        if (line.startsWith("**")) {
          return <p key={i} className="text-gray-700">{line.replace(/\*\*/g, "")}</p>
        }
        if (/^\d+\./.test(line)) {
          return <p key={i} className="text-gray-700 pl-2">{line}</p>
        }
        if (line.startsWith("---")) {
          return <hr key={i} className="border-gray-200 my-2" />
        }
        if (line.startsWith("*")) {
          return <p key={i} className="text-[10px] text-gray-400 italic">{line.replace(/\*/g, "")}</p>
        }
        if (line.trim() === "") {
          return <div key={i} className="h-1" />
        }
        return <p key={i} className="text-gray-700">{line}</p>
      })}
    </div>
  )
}

export function FinalReport() {
  const { state } = useMADAN()
  const [activeTab, setActiveTab] = useState<"markdown" | "json">("markdown")
  const [copied, setCopied] = useState(false)
  const [showSample, setShowSample] = useState(false)

  if (!state.result) {
    return (
      <div className="flex flex-col gap-4">
        <div className="border border-dashed border-gray-300 bg-gray-50 p-4 flex items-center justify-between">
          <p className="text-[11px] text-gray-400 italic">
            Audit report will appear here after the structured audit completes.
          </p>
          <button
            onClick={() => setShowSample(!showSample)}
            className="text-[10px] px-3 py-1.5 border border-gray-300 text-gray-600 hover:border-gray-600 transition-all font-semibold shrink-0 ml-4"
          >
            {showSample ? "Hide Sample" : "View Sample Report"}
          </button>
        </div>
        {showSample && (
          <div>
            <p className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2">
              Sample Output — AI Hiring System Audit
            </p>
            <SampleReportView />
          </div>
        )}
      </div>
    )
  }

  const markdownContent = generateMarkdownReport(state.scenario, state.agents, state.messages, state.result)
  const jsonContent = generateJSONExport(state.scenario, state.agents, state.messages, state.result)
  const content = activeTab === "markdown" ? markdownContent : jsonContent

  async function handleCopy() {
    await navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  function handleDownload() {
    const blob = new Blob([content], {
      type: activeTab === "markdown" ? "text/markdown" : "application/json",
    })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `ddat-audit-${state.scenario.title.replace(/\s+/g, "-").toLowerCase()}.${activeTab === "markdown" ? "md" : "json"}`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <div className="flex gap-1">
          <button
            className={`text-[10px] px-3 py-1.5 font-semibold border transition-all ${
              activeTab === "markdown"
                ? "bg-gray-900 text-white border-gray-900"
                : "bg-white text-gray-600 border-gray-200 hover:border-gray-400"
            }`}
            onClick={() => setActiveTab("markdown")}
          >
            Markdown Preview
          </button>
          <button
            className={`text-[10px] px-3 py-1.5 font-semibold border transition-all ${
              activeTab === "json"
                ? "bg-gray-900 text-white border-gray-900"
                : "bg-white text-gray-600 border-gray-200 hover:border-gray-400"
            }`}
            onClick={() => setActiveTab("json")}
          >
            JSON Export
          </button>
        </div>
        <div className="flex gap-2">
          <button
            className="text-[10px] px-3 py-1.5 border border-gray-200 text-gray-600 hover:border-gray-400 transition-all"
            onClick={handleCopy}
          >
            {copied ? "Copied!" : "Copy"}
          </button>
          <button
            className="text-[10px] px-3 py-1.5 bg-gray-900 text-white hover:bg-gray-700 transition-all font-semibold"
            onClick={handleDownload}
          >
            Download Report
          </button>
        </div>
      </div>

      <pre className="text-[10px] leading-relaxed font-mono whitespace-pre-wrap bg-gray-50 border border-gray-200 p-4 overflow-auto max-h-[500px] text-gray-800">
        {content}
      </pre>
    </div>
  )
}
