import type { AuditAgent } from "@/types/madan"

export const AUDIT_AGENTS: AuditAgent[] = [
  {
    id: "scenario-parser",
    name: "Scenario Parser",
    role: "Structural decomposition of the system under audit",
    description: "Decomposes the audit scenario into its constituent layers: measurement objects, decision pathways, power relations, and structural presuppositions.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "measurement-auditor",
    name: "Measurement-Form Auditor",
    role: "Audits what is being measured and what is treated as non-existent",
    description: "Interrogates the ontological commitments of measurement: what counts as a valid input, what is systematically excluded, and what silences are built into the scoring form.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "transgression-auditor",
    name: "Transgression Auditor",
    role: "Detects cross-layer category violations between physics/biology/psychology/sociology/philosophy",
    description: "Identifies when explanatory frameworks from one ontological layer are illegitimately applied to another — biology used to explain sociology, or physics used to ground ethics.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "reachable-state-auditor",
    name: "Reachable-State Auditor",
    role: "Evaluates impact on R(x): the set of futures accessible to affected subjects",
    description: "Maps whether the system expands or contracts the reachable state space R(x) of those evaluated — including second-order effects on future opportunity, mobility, and self-determination.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "nine-rates-auditor",
    name: "Nine-Rates Auditor",
    role: "Evaluates each of the nine generative rates from -5 to +5 with rationale",
    description: "Applies the full DDAT nine-rate framework to the scenario, generating a scored profile across IGR, PDF-GR, MGR, D-RGR, SRGR, TIGR, RCR, FGR, and HGR.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "reentry-auditor",
    name: "Re-Entry Auditor",
    role: "Evaluates whether failure, misclassification, or low scores permit re-entry",
    description: "Assesses the quality, accessibility, and structural fairness of re-entry pathways for those scored low, penalized, or excluded by the system.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "body-load-auditor",
    name: "Body-Load Auditor",
    role: "Audits chronic surveillance load, self-censorship, fatigue, and somatic attrition",
    description: "Quantifies the cumulative cognitive, emotional, and physiological toll of operating under continuous evaluation — including anticipatory anxiety, behavioral modification, and somatic cost.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "institution-fixation-auditor",
    name: "Institution-Fixation Auditor",
    role: "Detects whether scores/rankings have become ontological rather than instrumental",
    description: "Detects reification: the process by which scores shift from being tools of measurement to being treated as facts about reality, identity, or moral worth.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "genealogy-auditor",
    name: "Genealogy Auditor",
    role: "Traces intellectual and institutional lineage of the system's core assumptions",
    description: "Excavates the historical, political, and institutional origins of the system's foundational assumptions — identifying whose interests were embedded at conception.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "red-team-auditor",
    name: "Red Team Auditor",
    role: "Attacks overclaiming, unverified propositions, pseudoscience, and measurement overreach",
    description: "Stress-tests all audit conclusions, attacks weak evidentiary claims, challenges causal overclaims, and identifies where the system's defenders would push back most forcefully.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "synthesis-agent",
    name: "Synthesis Agent",
    role: "Integrates all agent outputs into a coherent audit summary",
    description: "Draws together contradictions, agreements, and open questions from all audit perspectives into a structured synthesis that preserves complexity without flattening disagreement.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
  {
    id: "ddat-judge",
    name: "DDAT Judge",
    role: "Issues the final directional judgment based on all audit perspective outputs",
    description: "Delivers the final directional assessment of the system under audit, integrating all perspective outputs, the Directional Correctness Index (DCR), and unresolved contradictions into a structured judgment.",
    status: "idle",
    confidence: 0,
    riskFlags: [],
    messages: [],
    scores: {},
  },
]
